from typing import List, Literal

from pydantic import BaseModel, Field


class EvalCaseItem(BaseModel):
    """Single evaluation case sent by the Java service."""

    # MySQL eval_case.id, used to map metrics back to the source case.
    case_id: int = Field(..., description="MySQL eval_case.id")
    # User-facing evaluation question that will be answered by the RAG pipeline.
    question: str = Field(..., description="Evaluation question")
    # Reference answer used by Ragas as the baseline for context_recall and context_precision.
    ground_truth: str = Field(
        ...,
        description="Reference answer used as the Ragas baseline for context_recall and context_precision",
    )


class EvaluateRequest(BaseModel):
    """Request body posted by the Java service to start an async evaluation batch."""

    # MySQL eval_batch.id, used as the correlation id for task execution and callback.
    batch_id: int = Field(..., description="MySQL eval_batch.id")
    # Tenant id used by the RAG retrieval flow to select the Milvus collection: tenant_{tenant_id}_docs.
    tenant_id: int = Field(
        ...,
        description="Tenant id used to select the tenant-specific retrieval collection",
    )
    # Evaluation cases included in this batch.
    cases: List[EvalCaseItem] = Field(..., description="Evaluation case list")
    # Java callback endpoint for completed results, for example: http://app:8081/internal/eval/callback.
    callback_url: str = Field(
        ...,
        description="Java callback URL, for example http://app:8081/internal/eval/callback",
    )


class SingleEvalResult(BaseModel):
    """Evaluation result for one case in a batch callback payload."""

    # Source eval_case.id for this result.
    case_id: int = Field(..., description="Source evaluation case id")
    # Actual answer generated by the RAG system for the case question.
    model_answer: str = Field(..., description="Actual answer generated by the RAG system")
    # Context passages retrieved by the RAG system and used for metric calculation.
    contexts: List[str] = Field(..., description="Retrieved context passages")
    # Faithfulness score in the 0 to 1 range; None means only this metric failed.
    faithfulness: float | None = Field(
        None,
        description="Faithfulness score from 0 to 1; None means this metric failed",
    )
    # Answer relevancy score in the 0 to 1 range; None means only this metric failed.
    answer_relevancy: float | None = Field(
        None,
        description="Answer relevancy score from 0 to 1; None means this metric failed",
    )
    # Context recall score in the 0 to 1 range; None means only this metric failed.
    context_recall: float | None = Field(
        None,
        description="Context recall score from 0 to 1; None means this metric failed",
    )
    # Context precision score in the 0 to 1 range; None means only this metric failed.
    context_precision: float | None = Field(
        None,
        description="Context precision score from 0 to 1; None means this metric failed",
    )
    # Case-level error message; None means the case did not fail as a whole.
    error: str | None = Field(
        None,
        description="Case-level error message; None means the case did not fail",
    )


class BatchEvalResult(BaseModel):
    """Full batch evaluation result posted back to the Java callback endpoint."""

    # MySQL eval_batch.id for this callback payload.
    batch_id: int = Field(..., description="MySQL eval_batch.id")
    # Batch status. DONE means callback contains completed results; FAILED means the whole batch failed.
    status: Literal["DONE", "FAILED"] = Field(..., description="Batch status: DONE or FAILED")
    # Per-case evaluation results. Failed cases may contain None metric values and an error message.
    results: List[SingleEvalResult] = Field(..., description="Per-case evaluation results")
    # Mean faithfulness score across all non-None case values; None if no value is available.
    avg_faithfulness: float | None = Field(
        None,
        description="Mean faithfulness over non-None values; None if unavailable",
    )
    # Mean answer relevancy score across all non-None case values; None if no value is available.
    avg_answer_relevancy: float | None = Field(
        None,
        description="Mean answer relevancy over non-None values; None if unavailable",
    )
    # Mean context recall score across all non-None case values; None if no value is available.
    avg_context_recall: float | None = Field(
        None,
        description="Mean context recall over non-None values; None if unavailable",
    )
    # Mean context precision score across all non-None case values; None if no value is available.
    avg_context_precision: float | None = Field(
        None,
        description="Mean context precision over non-None values; None if unavailable",
    )
    # Batch-level error message; None means the batch did not fail as a whole.
    error: str | None = Field(
        None,
        description="Batch-level error message; None means the batch did not fail",
    )


class EvaluateResponse(BaseModel):
    """Synchronous response returned immediately after the evaluation task is accepted."""

    # Whether the async task was accepted; True means async processing has started.
    accepted: bool = Field(..., description="Whether the async evaluation task was accepted")
    # MySQL eval_batch.id accepted for async processing.
    batch_id: int = Field(..., description="Accepted eval_batch id")
    # Human-readable acceptance message. This is not the evaluation result; results are sent via callback_url.
    message: str = Field(
        ...,
        description="Immediate response message; evaluation results are sent asynchronously via callback_url",
    )


class HealthResponse(BaseModel):
    """Health check response returned by the Ragas sidecar."""

    # Fixed health status value.
    status: Literal["ok"] = Field("ok", description='Fixed value "ok"')
    # Fixed service name value.
    service: Literal["kb-ragas"] = Field("kb-ragas", description='Fixed value "kb-ragas"')
